apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-keycloak
  labels:
   app: example-keycloak
spec:
  instances: 2
  hostname:
    hostname: keycloak.localhost
  ingress:
    enabled: False

