load('ext://helm_resource', 'helm_resource', 'helm_repo')
load('ext://git_resource', 'git_checkout')

_ext_dir = os.getcwd()

def deploy_component(name, directory):
    return '%s/%s.yaml' % (directory, name)


def keycloak():
    keycloak_operator_dir = git_checkout('https://github.com/keycloak/keycloak-operator.git', '%s/.tilt/keycloak-operator' % _ext_dir)
    keycloak_deploy_dir = '%s/deploy' % keycloak_operator_dir
    keycloak_crds = listdir("%s/deploy/crds" % keycloak_operator_dir)
    keycloak_items = ['role', 'role_binding', 'service_account', 'operator']
    k8s_yaml(keycloak_crds)
    [k8s_yaml(deploy_component(component, keycloak_deploy_dir)) for component in keycloak_items]
    k8s_yaml(["%s/keycloak.yaml" % _ext_dir, "%s/keycloak-ingress.yaml" % _ext_dir])
    k8s_resource(new_name="keycloak", objects=["example-keycloak"], port_forwards=["9990"], labels=["keycloak"])
    k8s_resource(new_name="keycloak-operator", workload="keycloak-operator", labels=["keycloak"])
