load('ext://helm_resource', 'helm_resource', 'helm_repo')
load('ext://git_resource', 'git_checkout')

_ext_dir = os.getcwd()

def deploy_component(name, directory):
    return '%s/%s.yaml' % (directory, name)


def keycloak():
    keycloak_k8s_resources = git_checkout('https://github.com/keycloak/keycloak-k8s-resources.git#tags/21.0.0', '%s/.tilt/keycloak-k8s-resources' % _ext_dir)
    keycloak_operator_crds = ['%s/kubernetes/keycloaks.k8s.keycloak.org-v1.yml' % keycloak_k8s_resources, '%s/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml' % keycloak_k8s_resources]
    k8s_yaml(keycloak_operator_crds)
    keycloak_operator_resources = ['%s/kubernetes/kubernetes.yml' % keycloak_k8s_resources]
    k8s_yaml(keycloak_operator_resources)
    keycloak_realm_operator_dir = git_checkout('https://github.com/keycloak/keycloak-realm-operator', '%s/.tilt/keycloak-realm-operator' % _ext_dir)
    keycloak_realm_deploy_dir = '%s/deploy' % keycloak_realm_operator_dir
    keycloak_realm_crds = listdir("%s/deploy/crds" % keycloak_realm_operator_dir)
    keycloak_realm_items = ['role', 'role_binding', 'service_account', 'operator']
    k8s_yaml(keycloak_realm_crds)
    [k8s_yaml(deploy_component(component, keycloak_realm_deploy_dir)) for component in keycloak_realm_items]
    k8s_yaml(["%s/keycloak.yaml" % _ext_dir, "%s/keycloak-ingress.yaml" % _ext_dir])
    k8s_resource(new_name="keycloak", objects=["example-keycloak"], port_forwards=["9990"], labels=["keycloak"])
    k8s_resource(new_name="keycloak-operator", workload="keycloak-operator", labels=["keycloak"])
    k8s_resource(new_name="keycloak-realm-operator", workload="keycloak-realm-operator", labels=["keycloak"])
